const PROJECT_TYPE_ALL = '';
const PROJECT_TYPE_EVENTS = 'events';
const PROJECT_TYPE_EXHIBITION = 'exhibitions';
const PROJECT_TYPE_CONCERTS = 'concerts';
const PROJECT_TYPE_RETAIL = 'retail';
export {
  PROJECT_TYPE_ALL,
  PROJECT_TYPE_EVENTS,
  PROJECT_TYPE_EXHIBITION,
  PROJECT_TYPE_CONCERTS,
  PROJECT_TYPE_RETAIL,
};
